import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { ExplainabilityTrace, PipelineEvent } from "@/lib/aether/types";

export function ExplainabilitySheet({ trace, onClose }: { trace?: ExplainabilityTrace; onClose: () => void }) {
  return <Modal visible={Boolean(trace)} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><Pressable style={StyleSheet.absoluteFill} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><View><Text style={styles.kicker}>ANSWER TRACE</Text><Text style={styles.title}>How this answer was grounded</Text></View><Pressable accessibilityLabel="Close answer trace" onPress={onClose} hitSlop={12} style={styles.closeButton}><MaterialIcons name="close" size={21} color="#25303D" /></Pressable></View>{trace ? <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.summaryCard}><Summary label="Response" value={trace.mode === "local_model" ? "On-device model" : trace.mode === "extractive" ? "Local evidence" : "Not answered"} /><View style={styles.summaryDivider} /><Summary label="Evidence" value={`${trace.selectedEvidenceIds.length} selected`} /><View style={styles.summaryDivider} /><Summary label="Time" value={`${trace.latencyMs} ms`} /></View><Text style={styles.sectionTitle}>What happened</Text><View style={styles.timeline}>{trace.pipeline.map((event, index) => <PipelineRow key={`${event.stage}-${index}`} event={event} last={index === trace.pipeline.length - 1} />)}</View><View style={[styles.noteCard, trace.mode === "abstained" && styles.warningCard]}><MaterialIcons name={trace.mode === "abstained" ? "info-outline" : "verified-user"} size={19} color={trace.mode === "abstained" ? "#A2453D" : "#2F7B68"} /><Text style={styles.noteText}>{trace.abstentionReason ?? trace.runtimeNote}</Text></View></ScrollView> : null}</View></View></Modal>;
}

function Summary({ label, value }: { label: string; value: string }) { return <View style={styles.summaryItem}><Text style={styles.summaryLabel}>{label}</Text><Text style={styles.summaryValue}>{value}</Text></View>; }
function PipelineRow({ event, last }: { event: PipelineEvent; last: boolean }) { const color = event.status === "complete" ? "#2F7B68" : event.status === "fallback" ? "#A77A29" : "#8C9098"; const icon = event.status === "complete" ? "check" : event.status === "fallback" ? "shield" : "remove"; return <View style={styles.pipelineRow}><View style={styles.timelineMarker}><View style={[styles.statusDot, { backgroundColor: color }]}><MaterialIcons name={icon} size={12} color="#FFFFFF" /></View>{!last ? <View style={styles.timelineLine} /> : null}</View><View style={styles.pipelineCopy}><View style={styles.pipelineTitleRow}><Text style={styles.pipelineName}>{event.title}</Text>{event.durationMs ? <Text style={styles.pipelineDuration}>{event.durationMs} ms</Text> : null}</View><Text style={styles.pipelineDetail}>{event.detail}</Text></View></View>; }

const styles = StyleSheet.create({
  backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(24,34,48,0.3)" }, sheet: { minHeight: "54%", maxHeight: "88%", borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: "#FCFCFA", paddingHorizontal: 20, paddingBottom: 30 }, handle: { alignSelf: "center", width: 38, height: 4, borderRadius: 4, marginTop: 11, marginBottom: 17, backgroundColor: "#D7D8D4" }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }, kicker: { color: "#5B5BD6", fontSize: 10, lineHeight: 14, letterSpacing: 0.8, fontWeight: "800" }, title: { marginTop: 3, color: "#182230", fontSize: 21, lineHeight: 27, fontWeight: "800" }, closeButton: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 20, backgroundColor: "#F1F1EF" }, content: { paddingBottom: 16 }, summaryCard: { flexDirection: "row", alignItems: "stretch", paddingVertical: 12, borderRadius: 16, backgroundColor: "#F5F5F2", borderWidth: 1, borderColor: "#E7E7E3" }, summaryItem: { flex: 1, paddingHorizontal: 12 }, summaryDivider: { width: 1, backgroundColor: "#DFDFDA" }, summaryLabel: { color: "#7A7D86", fontSize: 10, lineHeight: 14, fontWeight: "700" }, summaryValue: { marginTop: 3, color: "#303945", fontSize: 12, lineHeight: 17, fontWeight: "800" }, sectionTitle: { marginTop: 23, marginBottom: 10, color: "#25303D", fontSize: 16, lineHeight: 21, fontWeight: "800" }, timeline: { paddingVertical: 1 }, pipelineRow: { flexDirection: "row", gap: 11, minHeight: 62 }, timelineMarker: { width: 20, alignItems: "center" }, statusDot: { width: 20, height: 20, borderRadius: 10, alignItems: "center", justifyContent: "center" }, timelineLine: { width: 1, flex: 1, marginTop: 4, backgroundColor: "#DFDFDA" }, pipelineCopy: { flex: 1, paddingBottom: 14 }, pipelineTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, pipelineName: { flex: 1, color: "#303945", fontSize: 14, lineHeight: 19, fontWeight: "800" }, pipelineDuration: { color: "#7A7D86", fontSize: 11, lineHeight: 15 }, pipelineDetail: { marginTop: 2, color: "#6F7480", fontSize: 12, lineHeight: 17 }, noteCard: { flexDirection: "row", gap: 10, marginTop: 10, padding: 14, borderRadius: 16, backgroundColor: "#F2F7F4" }, warningCard: { backgroundColor: "#FBF1EF" }, noteText: { flex: 1, color: "#3C5148", fontSize: 13, lineHeight: 19 },
});
