import { PropsWithChildren } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { useAether } from "@/lib/aether/provider";

export function FirstLaunchGate({ children }: PropsWithChildren) {
  const { hydrated, snapshot, acceptFirstLaunchNotice } = useAether();
  if (!hydrated) return <View style={styles.loading}><Text style={styles.loadingText}>Opening AETHER…</Text></View>;
  if (snapshot.acceptedNoticeAt) return <>{children}</>;
  return <View style={styles.root}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.mark}><MaterialIcons name="shield" size={33} color="#FFFFFF" /></View><Text style={styles.eyebrow}>AETHER PRIVACY-FIRST</Text><Text style={styles.title}>Your local evidence workspace</Text><Text style={styles.lead}>Before you begin, please understand what this mobile build does and does not do.</Text><Info icon="lock-outline" title="Offline is the default" copy="Imported text files, WAV recordings, conversations, and evidence chunks are stored in AETHER’s private local storage. Retrieval, citations, and pipeline inspection remain local." /><Info icon="auto-awesome" title="Online Explain is optional" copy="It is off by default. If you enable it and tap Explain online on a citation, only that selected snippet and its question are sent to the managed LLM service." /><Info icon="description" title="Supported evidence in v1.2" copy="TXT, MD, CSV, JSON, LOG, and RST files up to 12 MB, plus 16 kHz mono PCM WAV recordings up to 120 MB after local Whisper Base setup. PDF, DOCX, and images are still in progress." /><Info icon="graphic-eq" title="Timestamped audio evidence" copy="AETHER transcribes supported WAV recordings on-device into timestamped evidence segments. Tap an audio citation to replay its quoted time range." /><Info icon="visibility" title="Answers show their evidence" copy="AETHER cites selected local chunks, shows an Answer Trace with every pipeline stage, and uses INSUFFICIENT_EVIDENCE when imported files do not support an answer." /><Text style={styles.agreement}>By continuing, you confirm that you understand the local default, optional online explanation boundary, and responsibility for files and model packs you choose to import.</Text><Pressable style={styles.accept} onPress={acceptFirstLaunchNotice}><Text style={styles.acceptText}>I understand and continue</Text><MaterialIcons name="arrow-forward" size={19} color="#FFFFFF" /></Pressable><Text style={styles.footer}>Version 1.2 · Local text and audio evidence</Text></ScrollView></View>;
}

function Info({ icon, title, copy }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; copy: string }) { return <View style={styles.info}><View style={styles.infoIcon}><MaterialIcons name={icon} size={20} color="#1B6EF3" /></View><View style={styles.infoCopy}><Text style={styles.infoTitle}>{title}</Text><Text style={styles.infoText}>{copy}</Text></View></View>; }

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#F7F9FC" }, loading: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#F7F9FC" }, loadingText: { color: "#607089", fontSize: 14 }, content: { padding: 28, paddingTop: 72, paddingBottom: 42 }, mark: { width: 64, height: 64, alignItems: "center", justifyContent: "center", borderRadius: 22, backgroundColor: "#10233D", shadowColor: "#10233D", shadowOpacity: 0.17, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 5 }, eyebrow: { marginTop: 23, color: "#0F8A83", fontSize: 11, lineHeight: 15, fontWeight: "800", letterSpacing: 1.4 }, title: { marginTop: 7, color: "#10233D", fontSize: 30, lineHeight: 36, fontWeight: "800" }, lead: { marginTop: 10, color: "#607089", fontSize: 15, lineHeight: 22 }, info: { flexDirection: "row", gap: 12, marginTop: 13, padding: 14, borderRadius: 17, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E2E8F0" }, infoIcon: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#E7F0FF" }, infoCopy: { flex: 1 }, infoTitle: { color: "#10233D", fontSize: 14, lineHeight: 19, fontWeight: "800" }, infoText: { marginTop: 3, color: "#607089", fontSize: 12, lineHeight: 17 }, agreement: { marginTop: 22, color: "#496078", fontSize: 12, lineHeight: 18, textAlign: "center" }, accept: { minHeight: 54, marginTop: 16, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9, borderRadius: 16, backgroundColor: "#1B6EF3" }, acceptText: { color: "#FFFFFF", fontSize: 15, lineHeight: 20, fontWeight: "800" }, footer: { marginTop: 14, color: "#8290A5", fontSize: 11, lineHeight: 15, textAlign: "center" },
});
