import { Pressable, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { AudioModelState, ResourceTelemetry, RuntimeState } from "@/lib/aether/types";

function formatStorage(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
export function ResourceBar({ telemetry, runtime, audioModel, onRefresh }: { telemetry: ResourceTelemetry; runtime: RuntimeState; audioModel: AudioModelState; onRefresh: () => void }) {
  return <View style={styles.wrap}><View style={styles.workspaceRow}><View style={styles.workspaceCopy}><Text style={styles.label}>WORKSPACE</Text><Text style={styles.value}>{telemetry.chunkCount} evidence segment{telemetry.chunkCount === 1 ? "" : "s"} · {formatStorage(telemetry.sourceBytes)}</Text></View><View style={styles.runtimePill}><View style={[styles.dot, runtime.loaded ? styles.readyDot : styles.idleDot]} /><Text style={styles.runtimeText}>{runtime.loaded ? "LLM ready" : "Evidence mode"}</Text></View><Pressable accessibilityLabel="Refresh workspace status" onPress={onRefresh} style={styles.refresh}><MaterialIcons name="refresh" size={18} color="#5B5BD6" /></Pressable></View><Text style={styles.detail}>{audioModel.installed ? "Whisper Base ready for WAV evidence" : "Add Whisper Base to index private WAV evidence"}</Text></View>;
}
const styles = StyleSheet.create({ wrap: { marginHorizontal: 20, marginBottom: 8, paddingHorizontal: 14, paddingVertical: 11, borderRadius: 16, backgroundColor: "#F5F5F2", borderWidth: 1, borderColor: "#E7E7E3" }, workspaceRow: { flexDirection: "row", alignItems: "center", gap: 10 }, workspaceCopy: { flex: 1 }, label: { color: "#7A7D86", fontSize: 10, lineHeight: 13, fontWeight: "800", letterSpacing: 0.7 }, value: { marginTop: 2, color: "#2B3542", fontSize: 13, lineHeight: 18, fontWeight: "700" }, runtimePill: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 99, backgroundColor: "#FFFFFF" }, dot: { width: 6, height: 6, borderRadius: 3 }, readyDot: { backgroundColor: "#2F7B68" }, idleDot: { backgroundColor: "#8C92A0" }, runtimeText: { color: "#535A66", fontSize: 11, lineHeight: 14, fontWeight: "700" }, refresh: { width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#FFFFFF" }, detail: { marginTop: 8, color: "#737780", fontSize: 11, lineHeight: 15 } });
