"""Query planner service using Granite 4 Tiny H for query intent analysis and sub-query decomposition."""

from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from backend.services.model_manager import model_manager

logger = logging.getLogger(__name__)


class QueryPlan(BaseModel):
    """Execution plan generated by the planner agent."""

    primary_modality: str = Field(default="text")
    sub_queries: List[str] = Field(default_factory=list)
    filters: Dict[str, Any] = Field(default_factory=dict)
    requires_calculation: bool = Field(default=False)


PLANNER_SYSTEM_PROMPT = (
    "You are a query planner for an evidence retrieval system. Analyze the user's question and output a JSON plan. "
    "Determine if the query needs text search, calculation, or temporal filtering. "
    "Output format MUST be strictly JSON with keys: 'primary_modality' (string, default 'text'), "
    "'sub_queries' (list of strings), 'filters' (object), 'requires_calculation' (boolean)."
)


class QueryPlannerService:
    """Planner service wrapping Granite LLM for structured query planning."""

    async def plan_query(self, query: str) -> QueryPlan:
        """Analyze query intent and generate a QueryPlan object.

        Args:
            query: Raw user query string.

        Returns:
            Validated QueryPlan object.
        """
        if not query or not query.strip():
            return QueryPlan(primary_modality="text", sub_queries=[], filters={}, requires_calculation=False)

        logger.info("Planning query: '%s'", query)

        try:
            granite = model_manager.get("granite")
            messages = [
                {"role": "system", "content": PLANNER_SYSTEM_PROMPT},
                {"role": "user", "content": f"Create a search plan for query: {query}"},
            ]

            response = granite.create_chat_completion(
                messages=messages,
                temperature=0.1,
                max_tokens=128,
            )

            output_text = response["choices"][0]["message"]["content"].strip()
            logger.debug("Raw planner output: %s", output_text)

            plan = self._parse_json_plan(output_text, query)
            logger.info("Generated plan: sub_queries=%s, filters=%s", plan.sub_queries, plan.filters)
            return plan

        except Exception as exc:
            logger.error("Planner agent failed for query '%s': %s. Falling back to default plan.", query, exc)
            return QueryPlan(
                primary_modality="text",
                sub_queries=[query],
                filters={},
                requires_calculation=False,
            )

    def _parse_json_plan(self, output_text: str, original_query: str) -> QueryPlan:
        """Extract and parse JSON from model response text."""
        # Try to locate JSON block within markdown ```json ... ``` or raw string
        match = re.search(r"\{.*\}", output_text, re.DOTALL)
        if match:
            json_str = match.group(0)
        else:
            json_str = output_text

        try:
            data = json.loads(json_str)
            sub_queries = data.get("sub_queries", [])
            if not isinstance(sub_queries, list) or not sub_queries:
                sub_queries = [original_query]

            return QueryPlan(
                primary_modality=str(data.get("primary_modality", "text")),
                sub_queries=[str(sq) for sq in sub_queries],
                filters=data.get("filters", {}) if isinstance(data.get("filters"), dict) else {},
                requires_calculation=bool(data.get("requires_calculation", False)),
            )
        except (json.JSONDecodeError, TypeError, ValueError) as exc:
            logger.warning("Failed to parse JSON from planner output: %s. Using default plan.", exc)
            return QueryPlan(
                primary_modality="text",
                sub_queries=[original_query],
                filters={},
                requires_calculation=False,
            )


query_planner_service = QueryPlannerService()
