"""Query planner service using Granite 4 Tiny H for query intent analysis and sub-query decomposition."""

from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from backend.services.model_manager import model_manager

logger = logging.getLogger(__name__)


class QueryPlan(BaseModel):
    """Execution plan generated by the planner agent."""

    primary_modality: str = Field(default="text")
    sub_queries: List[str] = Field(default_factory=list)
    filters: Dict[str, Any] = Field(default_factory=dict)
    requires_calculation: bool = Field(default=False)


# Allowed modalities for this text-only system
_ALLOWED_MODALITIES = {"text", "audio", "temporal", "mixed"}

PLANNER_SYSTEM_PROMPT = (
    "You are a query planner for a TEXT-ONLY evidence retrieval system. "
    "Analyze the user's question and output a JSON plan.\n\n"
    "RULES:\n"
    "1) primary_modality MUST be one of: text, audio, temporal, mixed. "
    "NEVER use 'image' — this system has NO vision capabilities.\n"
    "2) If the query is a single word or very short phrase, default to 'text' "
    "unless it explicitly mentions audio, voice notes, video, or timestamps.\n"
    "3) sub_queries: break complex queries into 1-3 focused search strings.\n"
    "4) Output ONLY valid JSON. No markdown, no explanation.\n\n"
    "FEW-SHOT EXAMPLES:\n"
    'Query: "model" → {"primary_modality": "text", "sub_queries": ["model"], "filters": {}, "requires_calculation": false}\n'
    'Query: "what did the voice note say" → {"primary_modality": "audio", "sub_queries": ["voice note content"], "filters": {}, "requires_calculation": false}\n'
    'Query: "diagram of the panel" → {"primary_modality": "text", "sub_queries": ["panel diagram description"], "filters": {}, "requires_calculation": false}\n'
    'Query: "when did the failure happen" → {"primary_modality": "temporal", "sub_queries": ["failure event timestamp"], "filters": {}, "requires_calculation": false}\n\n'
    "OUTPUT FORMAT (strict JSON):\n"
    '{"primary_modality": "text", "sub_queries": [...], "filters": {}, "requires_calculation": false}'
)

REFORMULATION_PROMPT = (
    "You are a search query reformulator. The original search query returned weak evidence.\n\n"
    "Given the original query and feedback about why the evidence was weak, "
    "suggest 1-3 alternative search queries that might find better evidence.\n\n"
    "RULES:\n"
    "1) Each query should approach the topic from a different angle or use different keywords.\n"
    "2) Keep queries concise (under 15 words each).\n"
    "3) Output ONLY a JSON array of strings. No other text.\n"
    "Example output: [\"alternative query 1\", \"alternative query 2\"]"
)


class QueryPlannerService:
    """Planner service wrapping Granite LLM for structured query planning."""

    async def plan_query(self, query: str) -> QueryPlan:
        """Analyze query intent and generate a QueryPlan object.

        Args:
            query: Raw user query string.

        Returns:
            Validated QueryPlan object.
        """
        if not query or not query.strip():
            return QueryPlan(primary_modality="text", sub_queries=[], filters={}, requires_calculation=False)

        logger.info("Planning query: '%s'", query)

        try:
            granite = model_manager.get("granite")
            messages = [
                {"role": "system", "content": PLANNER_SYSTEM_PROMPT},
                {"role": "user", "content": f"Create a search plan for query: {query}"},
            ]

            response = granite.create_chat_completion(
                messages=messages,
                temperature=0.1,
                max_tokens=128,
            )

            output_text = response["choices"][0]["message"]["content"].strip()
            logger.debug("Raw planner output: %s", output_text)

            plan = self._parse_json_plan(output_text, query)
            logger.info("Generated plan: sub_queries=%s, filters=%s", plan.sub_queries, plan.filters)
            return plan

        except Exception as exc:
            logger.error("Planner agent failed for query '%s': %s. Falling back to default plan.", query, exc)
            return QueryPlan(
                primary_modality="text",
                sub_queries=[query],
                filters={},
                requires_calculation=False,
            )

    async def reformulate_query(
        self, original_query: str, feedback: str
    ) -> List[str]:
        """Generate alternative search queries when initial retrieval is weak.

        Uses the already-loaded Granite model to suggest 1-3 reformulated
        queries based on the original query and quality feedback.

        Args:
            original_query: The original user query that produced weak evidence.
            feedback: Human-readable string describing why evidence was weak.

        Returns:
            List of 1-3 alternative query strings. Falls back to
            ``[original_query]`` if reformulation fails.
        """
        logger.info("Reformulating query: '%s' (feedback: %s)", original_query, feedback)

        try:
            granite = model_manager.get("granite")
            user_content = (
                f"Original query: {original_query}\n"
                f"Feedback: {feedback}\n\n"
                f"Suggest 1-3 alternative search queries as a JSON array:"
            )
            messages = [
                {"role": "system", "content": REFORMULATION_PROMPT},
                {"role": "user", "content": user_content},
            ]

            response = granite.create_chat_completion(
                messages=messages,
                temperature=0.3,
                max_tokens=128,
            )

            output_text = response["choices"][0]["message"]["content"].strip()
            logger.debug("Raw reformulation output: %s", output_text)

            queries = self._parse_query_list(output_text, original_query)
            logger.info("Reformulated queries: %s", queries)
            return queries

        except Exception as exc:
            logger.error("Reformulation failed for '%s': %s. Using original query.", original_query, exc)
            return [original_query]

    def _parse_json_plan(self, output_text: str, original_query: str) -> QueryPlan:
        """Extract and parse JSON from model response text."""
        # Try to locate JSON block within markdown ```json ... ``` or raw string
        match = re.search(r"\{.*\}", output_text, re.DOTALL)
        if match:
            json_str = match.group(0)
        else:
            json_str = output_text

        try:
            data = json.loads(json_str)
            sub_queries = data.get("sub_queries", [])
            if not isinstance(sub_queries, list) or not sub_queries:
                sub_queries = [original_query]

            # Enforce allowed modalities — reject "image" and any invalid value
            raw_modality = str(data.get("primary_modality", "text")).lower().strip()
            if raw_modality not in _ALLOWED_MODALITIES:
                logger.warning(
                    "Planner returned invalid modality '%s'. Forcing 'text'.", raw_modality
                )
                raw_modality = "text"

            return QueryPlan(
                primary_modality=raw_modality,
                sub_queries=[str(sq) for sq in sub_queries],
                filters=data.get("filters", {}) if isinstance(data.get("filters"), dict) else {},
                requires_calculation=bool(data.get("requires_calculation", False)),
            )
        except (json.JSONDecodeError, TypeError, ValueError) as exc:
            logger.warning("Failed to parse JSON from planner output: %s. Using default plan.", exc)
            return QueryPlan(
                primary_modality="text",
                sub_queries=[original_query],
                filters={},
                requires_calculation=False,
            )

    def _parse_query_list(self, output_text: str, fallback_query: str) -> List[str]:
        """Extract a JSON list of query strings from model response text.

        Args:
            output_text: Raw model output (may contain markdown fences).
            fallback_query: Query to return if parsing fails.

        Returns:
            List of query strings (1-3 items).
        """
        # Try to locate JSON array
        match = re.search(r"\[.*\]", output_text, re.DOTALL)
        if match:
            json_str = match.group(0)
        else:
            json_str = output_text

        try:
            data = json.loads(json_str)
            if isinstance(data, list) and data:
                queries = [str(q).strip() for q in data if str(q).strip()]
                if queries:
                    return queries[:3]  # Cap at 3
        except (json.JSONDecodeError, TypeError, ValueError) as exc:
            logger.warning("Failed to parse reformulated queries: %s. Using fallback.", exc)

        return [fallback_query]


query_planner_service = QueryPlannerService()

